services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "${API_PORT:-5002}:5002"
    volumes:
      - ./api:/api
    networks:
      - default
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    networks:
      - default
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  spa:
    build:
      context: .
      dockerfile: docker/spa.Dockerfile
    ports:
      - "${SPA_PORT:-4200}:4200"
    volumes:
      - ./spa:/spa
    networks:
      - default
    depends_on:
      - api

networks:
  default:
    driver: bridge